In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

In [2]:
from sklearn.preprocessing import PolynomialFeatures

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
features,target=make_regression(n_samples=100,n_features=2,n_informative=2,noise=0.02,coef=False,random_state=42,
                                n_targets=1)

In [5]:
features

array([[-1.1913035 ,  0.65655361],
       [ 0.05820872, -1.1429703 ],
       [ 0.58685709,  2.19045563],
       [ 0.47323762, -0.07282891],
       [ 0.73846658,  0.17136828],
       [-0.88951443, -0.81581028],
       [-1.91877122, -0.02651388],
       [-0.44651495,  0.85639879],
       [ 0.81252582,  1.35624003],
       [ 1.14282281,  0.75193303],
       [-1.10633497, -1.19620662],
       [ 0.62566735, -0.85715756],
       [-0.60063869, -0.29169375],
       [-0.39210815, -1.46351495],
       [-0.23415337, -0.23413696],
       [-0.84679372, -1.51484722],
       [ 0.91540212,  0.32875111],
       [ 0.32408397, -0.38508228],
       [ 0.09707755,  0.96864499],
       [-0.07201012,  1.0035329 ],
       [-0.46341769, -0.46572975],
       [-1.06230371,  0.47359243],
       [ 1.57921282,  0.76743473],
       [ 0.01300189,  1.45353408],
       [-0.91942423,  1.54993441],
       [-0.21967189,  0.35711257],
       [ 0.00511346, -0.23458713],
       [-1.32818605,  0.19686124],
       [-0.11564828,

In [6]:
interaction=PolynomialFeatures(degree=3,include_bias=False,interaction_only=True)
                              

In [7]:
features_interaction=interaction.fit_transform(features)

In [8]:
features_interaction

array([[-1.19130350e+00,  6.56553609e-01, -7.82154610e-01],
       [ 5.82087184e-02, -1.14297030e+00, -6.65308363e-02],
       [ 5.86857094e-01,  2.19045563e+00,  1.28548442e+00],
       [ 4.73237625e-01, -7.28289127e-02, -3.44653816e-02],
       [ 7.38466580e-01,  1.71368281e-01,  1.26549749e-01],
       [-8.89514430e-01, -8.15810285e-01,  7.25675020e-01],
       [-1.91877122e+00, -2.65138754e-02,  5.08740610e-02],
       [-4.46514952e-01,  8.56398794e-01, -3.82394867e-01],
       [ 8.12525822e-01,  1.35624003e+00,  1.10198004e+00],
       [ 1.14282281e+00,  7.51933033e-01,  8.59326225e-01],
       [-1.10633497e+00, -1.19620662e+00,  1.32340522e+00],
       [ 6.25667348e-01, -8.57157556e-01, -5.36295495e-01],
       [-6.00638690e-01, -2.91693750e-01,  1.75202552e-01],
       [-3.92108153e-01, -1.46351495e+00,  5.73856143e-01],
       [-2.34153375e-01, -2.34136957e-01,  5.48239586e-02],
       [-8.46793718e-01, -1.51484722e+00,  1.28276311e+00],
       [ 9.15402118e-01,  3.28751110e-01

In [10]:
regression=LinearRegression()

In [11]:
regression


LinearRegression()

In [13]:
model=regression.fit(features_interaction,target)

In [14]:
model

LinearRegression()

In [15]:
model.score(features_interaction,target)

0.9999999602893673

In [17]:
model.predict(features_interaction)[0]

-55.88516294960915

In [18]:
target[0]

-55.87308736550832

In [19]:
regression1=LinearRegression()


In [20]:
model1=regression1.fit(features,target)

In [21]:
model1

LinearRegression()

In [22]:
model1.score(features,target)

0.9999999595150364

In [23]:
features[0]

array([-1.1913035 ,  0.65655361])

In [24]:
## to create an interaction we have to multiply these two values/columns for every row

In [28]:
interaction_term=np.multiply(features[:,0],features[:,1])

In [29]:
interaction_term

array([-7.82154610e-01, -6.65308363e-02,  1.28548442e+00, -3.44653816e-02,
        1.26549749e-01,  7.25675020e-01,  5.08740610e-02, -3.82394867e-01,
        1.10198004e+00,  8.59326225e-01,  1.32340522e+00, -5.36295495e-01,
        1.75202552e-01,  5.73856143e-01,  5.48239586e-02,  1.28276311e+00,
        3.00939462e-01, -1.24798994e-01,  9.40336819e-02, -7.22645260e-02,
        2.15827408e-01, -5.03098998e-01,  1.21194276e+00,  1.88986929e-02,
       -1.42504725e+00, -7.84475928e-02, -1.19955114e-03, -2.61468347e-01,
        3.48221252e-02, -6.86778352e-02, -1.82380867e-01,  6.67296206e-02,
        9.69899786e-01, -1.57938256e-01,  5.95369083e-01,  3.29286209e-01,
        9.86448981e-01, -4.14057137e-01, -2.09356737e-01,  3.97663292e-01,
       -4.62941634e-01, -2.15317506e+00,  1.84957897e-01,  1.28240576e+00,
        1.55008645e-01, -1.00132931e+00,  2.30036224e-01, -1.00419873e+00,
       -3.30908757e-01,  4.05667360e-01,  2.59496444e-01, -5.01720362e-02,
       -2.33298544e-01, -

In [35]:
interaction_term[0]

-0.7821546100665004

In [36]:
features_interaction[:,2][0]

-0.7821546100665004

In [37]:
features_interaction[0]

array([-1.1913035 ,  0.65655361, -0.78215461])

## Fitting a Non-linear Relationship