In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures

In [5]:
features,target=make_regression(1000,n_features=4,n_informative=2,noise=0.02,random_state=42,coef=False)

In [6]:
features

array([[ 0.17775011,  1.95325914, -0.52587968, -0.70902096],
       [ 0.39580353,  1.38009135, -0.6255627 ,  1.47654035],
       [ 0.49191917, -0.57690366, -0.89841467,  0.95042384],
       ...,
       [ 0.71232216,  1.8296202 , -0.40968659,  0.89295387],
       [ 0.1975996 , -0.53523521,  1.31739407,  1.04955272],
       [-0.22747626,  1.00713334,  0.33614496, -0.97337884]])

In [8]:
target

array([-1.77101999e+01,  8.34000647e+01,  4.11717793e+01,  9.45554141e+01,
       -9.37691831e+01, -5.57191223e+01,  8.39551798e+01, -1.26667105e+02,
        2.33377730e+01, -8.63495824e+01,  4.88679742e+01,  5.65143678e+01,
        2.96248402e+00,  5.67024818e+01, -1.31102586e+01, -2.29302408e+01,
        1.16047659e+02, -3.18453088e+01,  5.09813109e+01, -4.15521915e+01,
       -3.93504162e+01, -2.74481456e+01,  1.04240633e+01,  3.72037386e+01,
       -7.64166898e+00, -2.08416372e+01,  1.98001604e+01, -1.33470078e+01,
        7.34507656e+01, -3.62503636e+00, -7.15432026e+01,  7.57720983e+01,
        3.51682553e+01,  3.85302017e+01,  4.38868261e+01,  6.59643754e-02,
        3.06194742e+01,  1.41646257e+01,  2.53502655e+01, -8.02490390e+01,
        1.75968088e+01,  2.61974568e+01,  9.17160997e+01, -3.24933135e+01,
        6.61383810e+00,  1.94001059e+01, -4.33995962e+00, -6.51321454e+00,
       -1.56079695e+01,  1.23341782e+02, -2.18034983e+01, -6.89166756e+01,
       -6.26667745e+01, -

In [14]:
interactions=PolynomialFeatures(degree=3,include_bias=False)

In [15]:
interactions

PolynomialFeatures(degree=3, include_bias=False)

In [16]:
interaction_features=interactions.fit_transform(features)

In [17]:
interaction_features.shape

(1000, 34)

In [18]:
regression=LinearRegression()

In [19]:
regression

LinearRegression()

In [21]:
model=regression.fit(interaction_features,target)

In [22]:
model

LinearRegression()

In [23]:
model.predict(interaction_features)[0]

-17.709942862463215

In [24]:
target[0]

-17.71019986617178

In [25]:
## plynomial regression was an extension of the linear regression that allow us to model the non-linear relationship


In [27]:
interaction_features[0]

array([ 1.77750106e-01,  1.95325914e+00, -5.25879676e-01, -7.09020958e-01,
        3.15951003e-02,  3.47192019e-01, -9.34751683e-02, -1.26028551e-01,
        3.81522126e+00, -1.02717928e+00, -1.38490166e+00,  2.76549434e-01,
        3.72859711e-01,  5.02710718e-01,  5.61603243e-03,  6.17134183e-02,
       -1.66152211e-02, -2.24015883e-02,  6.78155984e-01, -1.82581227e-01,
       -2.46166418e-01,  4.91566912e-02,  6.62758533e-02,  8.93568836e-02,
        7.45211578e+00, -2.00634732e+00, -2.70507183e+00,  5.40172708e-01,
        7.28291638e-01,  9.81924304e-01, -1.45431726e-01, -1.96079344e-01,
       -2.64365350e-01, -3.56432435e-01])

In [28]:
#polynomialFeatures degree was the attribute which wil define the maximum exponential value 
# we can scale up to

In [30]:
## reducting the variance regularization

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
from sklearn.preprocessing import PolynomialFeatures

In [32]:
## ridge regression and lasso regression

In [33]:
## in ridge regression we add an extra penality called L2 to the normal loss

In [34]:
## this helps us in the shrinking of the coeficients and make more grneralization and avoid overfitting

In [36]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

In [37]:
features,target=make_regression(1000,n_features=3,n_targets=1,n_informative=2,coef=False,
                                random_state=42,noise=0.2)

In [40]:
scaler=StandardScaler()

In [41]:
standard_feature=scaler.fit_transform(features)

In [42]:
standard_feature

array([[ 0.63462657,  0.26276433,  0.37408584],
       [ 0.08709541,  0.8079384 , -0.1487309 ],
       [ 3.0909556 ,  2.00123984,  0.57082095],
       ...,
       [-0.03331786,  1.0293018 ,  0.6470758 ],
       [ 0.20547089, -0.53585007,  0.24099641],
       [-1.11564801, -0.83868247,  0.58712496]])

In [45]:
regression=Ridge(alpha=0.5)

In [46]:
regression

Ridge(alpha=0.5)

In [48]:
model=regression.fit(standard_feature,target)

In [49]:
model

Ridge(alpha=0.5)

In [51]:
model.predict(standard_feature)[0]

87.64997341084869

In [52]:
target[0]

87.72771915288386

In [53]:
model.score(standard_score,target)

NameError: name 'standard_score' is not defined